-- MySQL Script generated by MySQL Workbench
-- Fri Sep  6 11:02:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgd` DEFAULT CHARACTER SET utf8 ;
USE `sgd` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usNombre` VARCHAR(45) NOT NULL,
  `usPassword` VARCHAR(45) NOT NULL,
  `usRol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;



CREATE TABLE archivos (
    idArchivo INT AUTO_INCREMENT PRIMARY KEY,
    tipo VARCHAR(100) NOT NULL,
    nombre VARCHAR(100) NOT NULL,       
    autor VARCHAR(100) NOT NULL,
	  ruta VARCHAR(255) NOT NULL,
    rutaCarpeta VARCHAR(255) NOT NULL,
	  privacidad VARCHAR(255) NOT NULL
);

INSERT INTO usuarios (usNombre, usPassword,usRol) VALUES ("jesus", "jesus123","Admin");
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
